import webbrowser
import pyautogui
from selenium import webdriver
import time
import datetime
driver = webdriver.Chrome()
driver.get('https://ilizone.iul.ac.in/login/index.php')
a=driver.find_element_by_xpath('//*[@id="username"]')
a.send_keys('1900102545')
b=driver.find_element_by_xpath('//*[@id="password"]')
b.send_keys('I@879@879@i')
c=driver.find_element_by_xpath('//*[@id="loginbtn"]')
c.click()
hour = int(datetime.datetime.now().hour)
x = datetime.datetime.now()
y=x.strftime("%a")
time.sleep(15)
if (y=="Mon") or (y=="Wed") or (y=="Fri"):
   if 21>=hour>=11:
      d=driver.find_element_by_xpath('//*[@id="page-container-0"]/div/ul/li[1]/div/div[1]/div/a')      
      d.click()
      pyautogui.press('enter')
      e=driver.find_element_by_xpath('//*[@id="module-331885"]/div/div/div[2]/div/a/span')      
      e.click()
      f=driver.find_element_by_xpath('//*[@id="region-main"]/div[1]/table[1]/tbody/tr[9]/td[3]/a')      
      f.click()
      g=driver.find_element_by_xpath('//*[@id="id_status_34739"]') 
      g.click() 
      h=driver.find_element_by_xpath('//*[@id="id_submitbutton"]')  
      h.click()
   elif 11>hour>=10:
      z=driver.find_element_by_xpath('//*[@id="paging-bar-0"]/ul/li[2]/a/span[1]/i')      
      z.click()
      time.sleep(5)
      d=driver.find_element_by_xpath('//*[@id="page-container-0"]/div[2]/ul/li[7]/div/div[1]/div/a')      
      d.click()
      pyautogui.press('enter')
      e=driver.find_element_by_xpath('//*[@id="module-332225"]/div/div/div[2]/div/a/span')      
      e.click()
      f=driver.find_element_by_xpath('//*[@id="region-main"]/div[1]/table[1]/tbody/tr[2]/td[3]/a')      
      f.click()
      g=driver.find_element_by_xpath('//*[@id="id_status_34739"]') 
      g.click() 
      h=driver.find_element_by_xpath('//*[@id="id_submitbutton"]')  
      h.click()
else:
   if 10>=hour>=7:
      d=driver.find_element_by_xpath('//*[@id="page-container-0"]/div[1]/ul/li[7]/div/div[1]/div/a')      
      d.click()
      pyautogui.press('enter')
      e=driver.find_element_by_xpath('//*[@id="module-332007"]/div/div/div[2]/div/a/span')      
      e.click()
      f=driver.find_element_by_xpath('//*[@id="region-main"]/div[1]/table[1]/tbody/tr[9]/td[3]/a')      
      f.click()
      g=driver.find_element_by_xpath('//*[@id="id_status_34739"]') 
      g.click() 
      h=driver.find_element_by_xpath('//*[@id="id_submitbutton"]')  
      h.click()          
   elif 13>=hour>=11:
      d=driver.find_element_by_xpath('//*[@id="page-container-0"]/div[1]/ul/li[10]/div/div[1]/div/a')      
      d.click()
      pyautogui.press('enter')
      e=driver.find_element_by_xpath('//*[@id="module-346985"]/div/div/div[2]/div/a/span')      
      e.click()
      f=driver.find_element_by_xpath('//*[@id="region-main"]/div[1]/table[1]/tbody/tr[9]/td[3]/a')      
      f.click()
      g=driver.find_element_by_xpath('//*[@id="id_status_34739"]') 
      g.click() 
      h=driver.find_element_by_xpath('//*[@id="id_submitbutton"]')  
      h.click()            